### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Parnenoia** [mycognitive/booking_timeslots_example_site#3]
What database should i use for the demo?
Cause none of the necessary modules are enabled

**Comment by kenorb** [comment]
The database is created from scratch when the site is built using [build_env.sh](https://github.com/mycognitive/booking_timeslots_example_site/blob/master/scripts/build_env.sh) script.

Which is the following `drush` command:

    $DRUSH site-install minimal --db-url=$DB_URL --account-pass=admin --yes --verbose
